version: '3.8'

services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
      - db

  backend:
    build:
      context: .
      dockerfile: build/backend.Dockerfile
    volumes:
      - ../backend:/go/src/app
    ports:
      - "8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: RhdskskQh!
      MYSQL_DATABASE: stop-and-count
      MYSQL_USER: bruine429
      MYSQL_PASSWORD: RhdskskQh!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
